### ISSUE TITLE
PortalContentPost.py failing with "Invalid group capability" error

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1428]
Used PortalContentExtract.py script to export user content against 10.4 portal. Used PortalContentPost.py to import to 10.4.1 portal and when the script tries to create groups for users the script fails with the following error:

Creating groups ...

Creating '2' group(s) for user '_user_'...
... group 'Gallery App Group'
ERROR:portalpy:Unable to create group.
ERROR:portalpy:Invalid group capability '[]'.
Traceback (most recent call last):
  File "C:\ops-server-config\Publish\Portal\PortalContentPost.py", line 1079, in <module>
    main()
  File "C:\ops-server-config\Publish\Portal\PortalContentPost.py", line 177, in main
    publish_portal(target_portal_address, contentpath, adminuser, adminpassword, users, hostname_map, specified_groups, id_mapping_file)
  File "C:\ops-server-config\Publish\Portal\PortalContentPost.py", line 261, in publish_portal
    newGroups = publish_user_groups(portaladmin, contentpath, userinfo, users)
  File "C:\ops-server-config\Publish\Portal\PortalContentPost.py", line 641, in publish_user_groups
    portal.reassign_group(groupId, username)
  File "C:\ops-server-config\Publish\Portal\portalpy\__init__.py", line 1263, in reassign_group
    resp = self.con.post('community/groups/' + id + '/reassign', postdata)
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by elinz** [comment]
The issue is that the createGroup endpoint in the portal sharing api only accepts form-data and not json. So the capabilities and tags list properties had to be converted to comma delimited strings.

**Comment by elinz** [comment]
Fixed. Change in master.
