### ISSUE TITLE
Modify PortalContentPost.py script so it doesn't update ids/urls in "esri" owned items

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1452]
I'm testing the script against 10.4.1 final it's throwing the following error when cycling through the esri owned items to update ids/urls. We don't need to update the ids or urls in the "esri_" owned items so modify the script to not process these items.

        Id: 1c783c741c234323903a9a7c6ac11f2e    Title: 'Check In' (Layer Template), Owner: 'esri_apps'

Traceback (most recent call last):
  File "C:\ops-server-config\Publish\Portal\PortalContentPost.py", line 1084, in <module>
    main()
  File "C:\ops-server-config\Publish\Portal\PortalContentPost.py", line 177, in main
    publish_portal(target_portal_address, contentpath, adminuser, adminpassword, users, hostname_map, specified_groups, id_mapping_file)
  File "C:\ops-server-config\Publish\Portal\PortalContentPost.py", line 313, in publish_portal
    update_post_publish(portaladmin, hostname_map, origIDToNewID)
  File "C:\ops-server-config\Publish\Portal\PortalContentPost.py", line 754, in update_post_publish
    update_item_data(portal, item, hostname_map, id_map)
  File "C:\ops-server-config\Publish\Portal\PortalContentPost.py", line 806, in update_item_data
    if itemdata.find(search_str) > -1:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4148: ordinal not in range(128)

**Comment by elinz** [comment]
Fixed in v.next. Merged into master.
